CREATE TABLE Favourite (
  ID                  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  UserID              integer(10) NOT NULL, 
  "Gallery ProjectID" integer(10) NOT NULL, 
  "Land CatalogID"    integer(10) NOT NULL, 
  FavouritesID        integer(10), 
  HomeSeekerID        integer(10), 
  FOREIGN KEY("Land CatalogID") REFERENCES "Land Catalog"(ID), 
  FOREIGN KEY("Gallery ProjectID") REFERENCES "Gallery Project"(ID), 
  FOREIGN KEY(UserID) REFERENCES "User"(ID));
CREATE TABLE Design (
  ID                INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  UserID2           integer(10) NOT NULL, 
  UserID            integer(10) NOT NULL, 
  DesignID          integer(10), 
  HomeSeekerID      integer(10), 
  ServiceType       integer(10), 
  NumberOfRooms     integer(10), 
  NumberOfBathrooms integer(10), 
  FOREIGN KEY(UserID) REFERENCES "User"(ID), 
  FOREIGN KEY(UserID2) REFERENCES "User"(ID));
CREATE TABLE "Gallery Project" (
  ID               INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  UserID2          integer(10) NOT NULL, 
  UserID           integer(10) NOT NULL, 
  ProjectID        integer(10), 
  ProjectName      integer(10), 
  ProfessionalID   integer(10), 
  ServiceType      integer(10), 
  Price            integer(10), 
  Year             integer(10), 
  NumberOfPictures integer(10), 
  PictureName      integer(10), 
  FOREIGN KEY(UserID) REFERENCES "User"(ID), 
  FOREIGN KEY(UserID2) REFERENCES "User"(ID));
CREATE TABLE "Land Catalog" (
  ID           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  UserID2      integer(10) NOT NULL, 
  UserID       integer(10) NOT NULL, 
  LandID       integer(10), 
  LandOwnerID  integer(10), 
  State        integer(10), 
  Address      integer(10), 
  Neighborhood integer(10), 
  Dimensions   integer(10), 
  Price        integer(10), 
  Status       integer(10), 
  FOREIGN KEY(UserID) REFERENCES "User"(ID), 
  FOREIGN KEY(UserID2) REFERENCES "User"(ID));
CREATE TABLE Payment (
  ID        INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  UserID    integer(10) NOT NULL, 
  PaymentID integer(10), 
  Payer     integer(10), 
  Receiver  integer(10), 
  Amount    integer(10), 
  Method    integer(10), 
  "Date"    integer(10), 
  FOREIGN KEY(UserID) REFERENCES "User"(ID));
CREATE TABLE Rating (
  ID        INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  UserID    integer(10) NOT NULL, 
  RatingID  integer(10), 
  Evaluator integer(10), 
  Evaluated integer(10), 
  Rating    integer(10), 
  Comments  integer(10), 
  FOREIGN KEY(UserID) REFERENCES "User"(ID));
CREATE TABLE "User" (
  ID                   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  Username5            integer(10), 
  Password             integer(10), 
  Usertype             integer(10), 
  Name                 integer(10), 
  Email                integer(10), 
  LandOwnerID          integer(10), 
  Username4            integer(10), 
  NumberOfProperties   integer(10), 
  ProfessionalID       integer(10), 
  Username3            integer(10), 
  Company              integer(10), 
  AdminID              integer(10), 
  Username2            integer(10), 
  AreaOfResponsability integer(10), 
  Position             integer(10), 
  HomeSeekerID         integer(10), 
  Username             integer(10), 
  Discriminator        varchar(255) NOT NULL);
